# Change these first
owner: Be-Square # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Landing page
    url: https://www.besquare.live
  - name: Test Get Tickets
    url: $TEST_GET_TICKETS_URL
  - name: Notification test5
    url: https://www.besquare.live/test5

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://www.besquare.live/public/assets/logo/be_square_logo_white_green.svg
  name: Be Square
#   introTitle:
#   introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
